import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { fetchUsage } from "../api";
export default function AdminUsage() {
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [since, setSince] = useState("");
    const [until, setUntil] = useState("");
    const load = () => {
        setLoading(true);
        fetchUsage({ since: since || undefined, until: until || undefined })
            .then(setData)
            .finally(() => setLoading(false));
    };
    useEffect(() => { load(); }, []);
    return (_jsxs("div", { children: [_jsxs("div", { className: "page-header", children: [_jsx("h1", { className: "page-title", children: "Usage Dashboard" }), _jsx("p", { className: "page-subtitle", children: "Platform-wide usage metrics and cost breakdown" })] }), _jsxs("div", { className: "filter-bar", children: [_jsx("label", { style: { fontSize: "0.82rem", color: "var(--text-secondary)" }, children: "From:" }), _jsx("input", { type: "date", value: since, onChange: (e) => setSince(e.target.value) }), _jsx("label", { style: { fontSize: "0.82rem", color: "var(--text-secondary)" }, children: "To:" }), _jsx("input", { type: "date", value: until, onChange: (e) => setUntil(e.target.value) }), _jsx("button", { className: "btn btn-secondary", onClick: load, children: "Apply" })] }), loading ? (_jsx("div", { className: "loading", children: "Loading usage data" })) : data ? (_jsxs(_Fragment, { children: [_jsxs("div", { className: "stat-grid", children: [_jsxs("div", { className: "stat-card stat-card-accent", children: [_jsx("div", { className: "stat-card-value", children: data.total_requests.toLocaleString() }), _jsx("div", { className: "stat-card-label", children: "Total Requests" })] }), _jsxs("div", { className: "stat-card stat-card-accent-success", children: [_jsx("div", { className: "stat-card-value", children: data.total_tokens.toLocaleString() }), _jsx("div", { className: "stat-card-label", children: "Total Tokens" })] }), _jsxs("div", { className: "stat-card stat-card-accent-warning", children: [_jsxs("div", { className: "stat-card-value", children: ["$", data.total_cost.toFixed(2)] }), _jsx("div", { className: "stat-card-label", children: "Total Cost" })] })] }), data.by_workspace.length > 0 && (_jsxs("div", { className: "detail-section", children: [_jsx("h2", { className: "detail-section-title", children: "Per-Workspace Breakdown" }), _jsx("div", { className: "table-container", children: _jsxs("table", { children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Workspace" }), _jsx("th", { children: "Requests" }), _jsx("th", { children: "Tokens" }), _jsx("th", { children: "Cost" })] }) }), _jsx("tbody", { children: data.by_workspace.map((ws) => (_jsxs("tr", { children: [_jsx("td", { style: { fontFamily: "var(--font-mono)", fontSize: "0.82rem" }, children: ws.workspace_id }), _jsx("td", { children: ws.total_requests.toLocaleString() }), _jsx("td", { children: ws.total_tokens.toLocaleString() }), _jsxs("td", { style: { fontFamily: "var(--font-mono)", fontSize: "0.82rem" }, children: ["$", ws.total_cost.toFixed(2)] })] }, ws.workspace_id))) })] }) })] }))] })) : (_jsx("div", { className: "card", style: { textAlign: "center", padding: 40, color: "var(--text-muted)" }, children: "No usage data available" }))] }));
}
